/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quran_management;
import java.sql.*;
import javax.swing.JScrollPane;
import javax.swing.JComboBox;
import javax.swing.JTable;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getString;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import static quran_management.GreetingMessagesScreen2.selected1;
import static quran_management.Para.selected;
/**
 *
 * @author Javeria
 */
public class HadithDisplayScreen extends javax.swing.JFrame {
static String selected3; 
    /**
     * Creates new form HadithDisplayScreen
     */
    public HadithDisplayScreen() {
        tableLoad();
		
	}
	
	 private void tableLoad() {
		 try{
	            java.sql.Connection mycon = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","oracle");
	            Statement stmt = mycon.createStatement();
	            
	            ResultSet rs = stmt.executeQuery("select CHAPTER,HADITH from HR.HADITH where NARRATOR='"+selected3+"'");
	          
	            
	            ResultSetMetaData rd = rs.getMetaData();
	            int c = rd.getColumnCount();
                   
                     DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
	            df.setRowCount(0);
	            while(rs.next()){
	                Vector v2 = new Vector();
	                for(int i = 1; i <= c; i++){
                                v2.add(rs.getString("CHAPTER"));
                                v2.add(rs.getString("HADITH"));
	                }
	                df.addRow(v2);
	            }
	        }
	        catch(Exception e){
                     System.out.println("Display Result for:"+" "+selected3);
	           // System.out.println(e.toString());
	        
	        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 102, 0));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setBackground(new java.awt.Color(153, 102, 0));
        jTextField2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("Hadiths");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, 30));

        jTextField3.setBackground(new java.awt.Color(153, 102, 0));
        jTextField3.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(204, 204, 204));
        jTextField3.setText("WAY TO JUNNAH");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, 30));

        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton9.setText("Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "CHAPTER", "HADITH"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 740, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
    
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        HadithScreen HS= new HadithScreen();
        HS.show();
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
//        TableColumnModel modelecolonne = jTable1.getColumnModel();
//        TableModel modele = jTable1.getModel();
//        int total = modelecolonne.getColumnCount();
//        for(int i=0;i<total;i++){
//            int taille=0;
//            int total2=modele.getRowCount();
//            for(int j=0;j<total2;j++){
//                if(modele.getValueAt(j, i)!=null){
//               int taille2=modele.getValueAt(j,i).toString().length()*7;
//               if(taille2>taille){
//                   taille=taille2;
//               }
//                }modelecolonne.getColumn(i).setPreferredWidth(taille);
//            }
//        }
     //   DefaultTableModel model1= new DefaultTableModel(data,columnNames);
        //jTable1.setModel(model1);
        jTable1.setRowHeight(50);
        TableColumnModel ColModel = jTable1.getColumnModel();
        ColModel.getColumn(0).setPreferredWidth(100);
       // TableColumnModel 
         //jTable1.setColumnHeight(50);
        try{
            java.sql.Connection mycon = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","oracle");
	    Statement stmt = mycon.createStatement();
            // ResultSet res =mystmt.executeQuery("Select JUZZ from HR.JUZ where JUZ_NAME = '"+selected+"'");
            PreparedStatement ps = mycon.prepareStatement("select CHAPTER,HADITH from HR.HADITH where NARRATOR='"+selected3+"'");
	    ResultSet rs = ps.executeQuery();
            DefaultTableModel tm = (DefaultTableModel)jTable1.getModel();
            
            tm.setRowCount(0);
            while (rs.next())
            {
                Object o[]={rs.getString("CHAPTER"),
                rs.getString("HADITH")
                };
                tm.addRow(o);
            }
       }
       catch(Exception e){
            
           //JOptionPane.showMessageDialog(this, e);
       }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HadithDisplayScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HadithDisplayScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HadithDisplayScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HadithDisplayScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//try{
// Class.forName("oracle.jdbc.driver.OracleDriver");
// Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","DB1project*");
// String query = "select CHAPTER, NARRATOR, HADITH from HADITH where NARRATOR= '"+"Abu Huraira"+"'";
// Statement s= con.createStatement();
// ResultSet rs = s.executeQuery(query);
// String str[]={"Chapter Name","Narrated By","Hadith"};
// String data[][]= new String [20][3];
// int i=0;
// while(rs.next()){
//   String chap = rs.getString("CHAPTER");
//                String  nar= rs.getString("NARRATOR");
//                String hd = rs.getString("HADITH");
//
//                data[i][0] =chap;
//                data[i][1] = nar;
//                data[i][2] = hd;
//                i++;
//            }
//
//            JTable jt = new JTable(data, str);
//
//            JScrollPane sp = new JScrollPane(jt);
//          
//           new HadithDisplayScreen().add(sp);
//           new HadithDisplayScreen().setVisible(true);
//           new HadithDisplayScreen().revalidate();
//           new HadithDisplayScreen().repaint(); 
// }
//
//catch (Exception e){
//System.out.println("Result Not Found");
//}
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HadithDisplayScreen().setVisible(true);
           
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
